/* Website/PWA regression. Browser install events are simulated, not an OS install. */
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),port=18126,base=`http://127.0.0.1:${port}`;
const output=process.env.QA_OUTPUT||path.join(root,'test-results','website');fs.mkdirSync(output,{recursive:true});
const server=spawn(process.env.QA_PYTHON||'python',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port',String(port),'--no-access-log'],{cwd:root,env:{...process.env,PLANTNET_API_KEY:''},stdio:['ignore','pipe','pipe']});
let browser;const errors=[];
async function ready(){for(let i=0;i<90;i++){try{if((await fetch(base+'/api/status')).ok)return;}catch{}await new Promise(r=>setTimeout(r,200));}throw Error('Server did not start');}
(async()=>{try{
 await ready();const options={headless:true};if(process.env.QA_CHROMIUM)options.executablePath=process.env.QA_CHROMIUM;if(process.env.QA_CHROMIUM_ARGS)options.args=JSON.parse(process.env.QA_CHROMIUM_ARGS);browser=await chromium.launch(options);
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#install-dialog').waitFor({state:'attached'});
 assert.match(await page.locator('h1').innerText(),/A little closer/);
 const session=await context.newCDPSession(page);const manifest=await session.send('Page.getAppManifest');assert.equal(manifest.errors.length,0);assert.equal(JSON.parse(manifest.data).start_url,'/app#scan');
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Overflow at ${width}`);if(width===1440||width===390)await page.screenshot({path:path.join(output,`website-${width}.png`),fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.locator('[data-install]').first().click();await page.locator('#install-dialog').waitFor({state:'visible'});assert.match(await page.locator('#install-dialog').innerText(),/Add to Home Screen/);await page.screenshot({path:path.join(output,'installation-mobile.png')});await page.getByRole('button',{name:'Close installation help'}).click();
 // Native prompt branch and dismissal: a click must invoke the supplied browser prompt.
 await page.evaluate(()=>{window.installPromptCalled=0;const e=new Event('beforeinstallprompt',{cancelable:true});e.prompt=async()=>{window.installPromptCalled++;};e.userChoice=Promise.resolve({outcome:'dismissed'});dispatchEvent(e);});
 await page.locator('[data-install]').first().click();assert.equal(await page.evaluate(()=>window.installPromptCalled),1);assert.match(await page.locator('[data-install-status]').innerText(),/dismissed/);assert.equal(await page.locator('#install-dialog').isVisible(),false);
 await page.getByRole('link',{name:'Photo privacy'}).click();assert.equal(await page.locator('#privacy').getAttribute('open'),'');
 await page.getByRole('link',{name:'Check plant health',exact:false}).click();await page.waitForFunction(()=>document.getElementById('coverage')?.textContent.includes('v1.3.0'));assert.equal(await page.locator('#mode-disease').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#health-engine').inputValue(),'plantnet');
 // Exercise real canvas preprocessing using a synthetic, visually complex image.
 const result=await page.evaluate(async()=>{const {preparePhoto}=await import('/photos.js');const canvas=document.createElement('canvas');canvas.width=2200;canvas.height=2200;const c=canvas.getContext('2d');const data=c.createImageData(2200,2200);let seed=101;for(let i=0;i<data.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;data.data[i]=seed&255;data.data[i+1]=(seed>>>8)&255;data.data[i+2]=(seed>>>16)&255;data.data[i+3]=255;}c.putImageData(data,0,0);const original=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.97));const resized=await preparePhoto(new File([original],'large.jpg',{type:'image/jpeg'}));const bitmap=await createImageBitmap(resized);let bad='';try{await preparePhoto(new File(['bad'],'bad.jpg',{type:'image/jpeg'}));}catch(e){bad=e.message;}const result={original:original.size,prepared:resized.size,width:bitmap.width,type:resized.type,bad};bitmap.close();return result;});
 assert.ok(result.original>result.prepared);assert.ok(result.prepared<=1_000_000);assert.ok(result.width<=1600);assert.equal(result.type,'image/jpeg');assert.match(result.bad,/could not be opened/);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(r=>navigator.serviceWorker.addEventListener('controllerchange',r,{once:true}));});
 // The same browser origin keeps its journal when moving from / to /app.
 await page.evaluate(async()=>{const {saveScan}=await import('/journal.js');await saveScan({id:'website-offline',created_at:new Date().toISOString(),note:'Saved before going offline',result:{id:'website-offline',created_at:new Date().toISOString(),status:'no_match',mode:'species',provider:'Pl@ntNet',candidates:[]},thumbnail:null});});
 await page.goto(base+'/#journal');await page.waitForURL('**/app#journal');await page.locator('.journal-card').waitFor();assert.match(await page.locator('.journal-card').innerText(),/Saved before going offline/);
 await page.locator('[data-view="guide"]').click();await page.locator('.guide-card').first().waitFor();await context.setOffline(true);await page.goto(base+'/app?mode=health#journal');await page.locator('.journal-card').waitFor();assert.match(await page.locator('.journal-card').innerText(),/Saved before going offline/);await page.locator('[data-view="guide"]').click();assert.equal(await page.locator('.guide-card').count(),15);await page.goto(base+'/');assert.match(await page.locator('h1').innerText(),/A little closer/);await context.setOffline(false);
 await page.evaluate(()=>dispatchEvent(new Event('appinstalled')));assert.equal(await page.locator('[data-install]').first().isDisabled(),true);assert.equal(await page.locator('[data-install]').first().innerText(),'App installed');
 const ios=await browser.newContext({viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',isMobile:true,hasTouch:true});const phone=await ios.newPage();await phone.goto(base);await phone.locator('[data-install]').first().click();assert.equal(await phone.locator('.lw-install-methods li').first().getAttribute('data-platform'),'ios');await ios.close();
 assert.deepEqual(errors,[]);console.log('PASS: landing at 320/390/768/1440 px; manifest; manual installation; simulated native install/dismiss/installed; iOS guidance; health deep link; real photo compression; old bookmarks; offline journal/guide/landing. No real OS installation or provider inference.');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
