export const copy = {
 en:{scanNav:'Leaf scan',journalNav:'My journal',guideNav:'Field guide',eyebrow:'YOUR POCKET FIELD GUIDE',hero:'A closer look.<br>A clearer next step.',intro:'Every leaf tells a story. Get a little help reading yours, with a photo and a few thoughtful next steps.',private:'Share photos with permission',start:'START WITH WHAT YOU SEE',scanTitle:"Let's look at your plant",health:'Check plant health',checkDisease:'Check disease & pests',identify:'Identify a plant',cropQuestion:'Which crop is this?',addPhotos:'Add your photos',uploadTitle:'One leaf. A little daylight.',uploadHint:'Drop a photo here, or choose from your device.',choose:'Choose photos',camera:'Use camera',addMore:'+ Add another view',analyze:'Read this leaf',working:'Looking at your photos…',photoTipTitle:'Make the leaf <br>the main character.',tip1:'Find soft daylight',tip2:'Fill the frame',tip3:'Show another side',journalTitle:'A record of small changes.',guideTitle:'Get to know your leaves.'},
 hi:{scanNav:'पत्ती जाँच',journalNav:'मेरी डायरी',guideNav:'फसल गाइड',eyebrow:'आपकी फसल का छोटा साथी',hero:'पत्ती को समझें।<br>अगला कदम जानें।',intro:'पत्ती की साफ़ तस्वीर लें। संभावित समस्या समझें और देखभाल के अगले कदम जानें।',private:'अनुमति से तस्वीर साझा करें',start:'शुरू करें एक तस्वीर से',scanTitle:'अपने पौधे को करीब से देखें',health:'पौधे की सेहत',checkDisease:'रोग और कीट की जाँच',identify:'पौधे की पहचान',cropQuestion:'यह कौन सी फसल है?',addPhotos:'तस्वीरें जोड़ें',uploadTitle:'एक पत्ती। अच्छी रोशनी।',uploadHint:'यहाँ तस्वीर डालें या अपने डिवाइस से चुनें।',choose:'तस्वीर चुनें',camera:'कैमरा खोलें',addMore:'+ दूसरी तस्वीर जोड़ें',analyze:'पत्ती की जाँच करें',working:'तस्वीरों की जाँच हो रही है…',photoTipTitle:'तस्वीर में पत्ती<br>साफ़ दिखाई दे।',tip1:'हल्की प्राकृतिक रोशनी',tip2:'पत्ती को पास से दिखाएँ',tip3:'दूसरी तरफ़ भी दिखाएँ',journalTitle:'बदलावों का अपना रिकॉर्ड।',guideTitle:'अपनी पत्तियों को पहचानें।'},
 gu:{scanNav:'પાનની તપાસ',journalNav:'મારી નોંધપોથી',guideNav:'પાક માર્ગદર્શિકા',eyebrow:'તમારા પાકની નાની માર્ગદર્શિકા',hero:'પાનને સમજો.<br>આગળનું પગલું જાણો.',intro:'પાનનો સ્પષ્ટ ફોટો લો. સંભવિત સમસ્યા સમજો અને સંભાળ માટેનાં આગળનાં પગલાં જાણો.',private:'મંજૂરીથી ફોટા શેર કરો',start:'એક ફોટાથી શરૂઆત કરો',scanTitle:'તમારા છોડને નજીકથી જુઓ',health:'છોડની તંદુરસ્તી',checkDisease:'રોગ અને જીવાત તપાસો',identify:'છોડની ઓળખ',cropQuestion:'આ કયો પાક છે?',addPhotos:'ફોટા ઉમેરો',uploadTitle:'એક પાન. સારો પ્રકાશ.',uploadHint:'અહીં ફોટો મૂકો અથવા તમારા ઉપકરણમાંથી પસંદ કરો.',choose:'ફોટો પસંદ કરો',camera:'કેમેરા ખોલો',addMore:'+ બીજો ફોટો ઉમેરો',analyze:'પાનની તપાસ કરો',working:'ફોટાની તપાસ થઈ રહી છે…',photoTipTitle:'ફોટામાં પાન<br>સ્પષ્ટ દેખાય.',tip1:'કુદરતી પ્રકાશ પસંદ કરો',tip2:'પાનને નજીકથી બતાવો',tip3:'બીજી બાજુ પણ બતાવો',journalTitle:'નાના ફેરફારોની નોંધ.',guideTitle:'તમારાં પાનને ઓળખો.'}
};
export function translate(lang) {
  const strings = copy[lang] || copy.en;
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {el.innerHTML = strings[el.dataset.i18n] || copy.en[el.dataset.i18n];});
}
